#!/bin/sh
while read oldrev newrev refname
do
    if [ ${refname} == "refs/heads/master" ]; then
        # Put function "check_error", "success", "error" and "section" in the scope
        source ./hooks/log_messages.sh

        # Set the necessary locations
        PROJECT_PATH=$(dirname `pwd`)
        APP_PATH=$(dirname ${PROJECT_PATH})

        GIT_WORK_TREE=${PROJECT_PATH} git checkout -f
        GIT_WORK_TREE=${PROJECT_PATH} git reset --hard

        section "Set project's environment"
        ENV_FILE=${APP_PATH}/.env
        for line in $(cat ${ENV_FILE}); do echo ${line}; done
        cp ${ENV_FILE} ${PROJECT_PATH}
        check_error $?

        section "Activate the virtual environment"
        source ${PROJECT_PATH}/env/bin/activate
        cd ${PROJECT_PATH}

        section "Install project requirements"
        pip install -e .
        check_error $?

        section "Apply the migrations"
        python manage.py migrate
        check_error $?

        section "Restart Apache server"
        . ${APP_PATH}/apache2/bin/restart
        check_error $?

        success "Deploy performed successfully"
    fi
done
