#!/usr/bin/env bash

source ./utils/set_paths.sh
source ${UTILS_PATH}/log_messages.sh

while read oldrev newrev refname; do
  log "Post-receive started."

  cd ${PROJECT_PATH}

  ${UTILS_PATH}/read_app_json.sh

  ${UTILS_PATH}/restart_server.sh

  log "Post-receive ended."
  echo ""
  success "Deployment performed successfully!"
done
