#!/usr/bin/env bash

source ./utils/set_paths.sh -b
${UTILS_PATH}/pull_updates.sh
source ${UTILS_PATH}/log_messages.sh

while read oldrev newrev refname; do
  if [ ${refname} == "refs/heads/master" ]; then
    git archive $newrev | tar -xC ${PROJECT_PATH}

    log "Start deployment process ($(date "${DATETIME_FORMAT}"))" 2>&1 | ${SAVE_TO_LOG}

    ./deploy.sh 2>&1 | ${SAVE_TO_LOG}
    if [ ${PIPESTATUS} ]; then # Solution source: http://stackoverflow.com/a/6871917/4694834
      check_error ${PIPESTATUS[0]}
    elif [ ${pipestatus} ]; then # Improvement for "zsh": https://unix.stackexchange.com/a/14276
      check_error ${pipestatus[0]}
    fi

    log "End deployment process ($(date "${DATETIME_FORMAT}"))\n" 2>&1 | ${SAVE_TO_LOG}
  else
    error "Not the master branch. Deployment process aborted."
    exit 1
  fi
done

exit 0
