#!/usr/bin/env bash

source ./utils/set_paths.sh
source ${UTILS_PATH}/log_messages.sh

${UTILS_PATH}/pull_updates.sh

while read oldrev newrev refname; do
  if [ ${refname} == "refs/heads/master" ]; then
    cp -r ${PROJECT_PATH} ${PROJECT_PATH}.backup
    git archive $newrev | tar -x -C ${PROJECT_PATH}

    ./deploy.sh
  else
    error "Not the master branch. Deployment process aborted."
    exit 1
  fi
done

exit 0
